services:
  minio:
    image: minio/minio:latest
    container_name: minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "9005:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

    volumes:
      - clickhouse_data:/var/lib/clickhouse

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  streamlit:
    image: python:3.11-slim
    container_name: streamlit
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    command: >
      sh -c "pip install -r requirements.txt && streamlit run app.py --server.address 0.0.0.0"
    depends_on:
      clickhouse:
        condition: service_healthy

  ingestion-engine:
    image: python:3.11-slim
    container_name: ingestion-engine

    working_dir: /app

    volumes:
      - ./ingestion:/app

    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PREFIX: ${MINIO_PREFIX}

      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}

    command: >
      sh -c "pip install -r requirements.txt && python ingest.py"

    depends_on:
      clickhouse:
        condition: service_healthy

      minio:
        condition: service_started

  dbt-runner:
    image: python:3.11-slim
    container_name: dbt-runner

    working_dir: /usr/app

    volumes:
      - ./dbt:/usr/app

    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}

    command: tail -f /dev/null

    depends_on:
      clickhouse:
        condition: service_healthy

volumes:
  minio_data:
  clickhouse_data:

networks:
  default:
    name: olist_network